# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aniquetahir/CLionProjects/cse570project2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aniquetahir/CLionProjects/cse570project2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aniquetahir/CLionProjects/cse570project2/CMakeFiles /Users/aniquetahir/CLionProjects/cse570project2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aniquetahir/CLionProjects/cse570project2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cse570project2

# Build rule for target.
cse570project2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cse570project2
.PHONY : cse570project2

# fast build rule for target.
cse570project2/fast:
	$(MAKE) -f CMakeFiles/cse570project2.dir/build.make CMakeFiles/cse570project2.dir/build
.PHONY : cse570project2/fast

#=============================================================================
# Target rules for targets named halfedge

# Build rule for target.
halfedge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 halfedge
.PHONY : halfedge

# fast build rule for target.
halfedge/fast:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/build
.PHONY : halfedge/fast

Core/Edge.o: Core/Edge.cpp.o

.PHONY : Core/Edge.o

# target to build an object file
Core/Edge.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Edge.cpp.o
.PHONY : Core/Edge.cpp.o

Core/Edge.i: Core/Edge.cpp.i

.PHONY : Core/Edge.i

# target to preprocess a source file
Core/Edge.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Edge.cpp.i
.PHONY : Core/Edge.cpp.i

Core/Edge.s: Core/Edge.cpp.s

.PHONY : Core/Edge.s

# target to generate assembly for a file
Core/Edge.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Edge.cpp.s
.PHONY : Core/Edge.cpp.s

Core/FException.o: Core/FException.cpp.o

.PHONY : Core/FException.o

# target to build an object file
Core/FException.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/FException.cpp.o
.PHONY : Core/FException.cpp.o

Core/FException.i: Core/FException.cpp.i

.PHONY : Core/FException.i

# target to preprocess a source file
Core/FException.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/FException.cpp.i
.PHONY : Core/FException.cpp.i

Core/FException.s: Core/FException.cpp.s

.PHONY : Core/FException.s

# target to generate assembly for a file
Core/FException.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/FException.cpp.s
.PHONY : Core/FException.cpp.s

Core/Face.o: Core/Face.cpp.o

.PHONY : Core/Face.o

# target to build an object file
Core/Face.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Face.cpp.o
.PHONY : Core/Face.cpp.o

Core/Face.i: Core/Face.cpp.i

.PHONY : Core/Face.i

# target to preprocess a source file
Core/Face.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Face.cpp.i
.PHONY : Core/Face.cpp.i

Core/Face.s: Core/Face.cpp.s

.PHONY : Core/Face.s

# target to generate assembly for a file
Core/Face.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Face.cpp.s
.PHONY : Core/Face.cpp.s

Core/HalfEdge.o: Core/HalfEdge.cpp.o

.PHONY : Core/HalfEdge.o

# target to build an object file
Core/HalfEdge.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/HalfEdge.cpp.o
.PHONY : Core/HalfEdge.cpp.o

Core/HalfEdge.i: Core/HalfEdge.cpp.i

.PHONY : Core/HalfEdge.i

# target to preprocess a source file
Core/HalfEdge.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/HalfEdge.cpp.i
.PHONY : Core/HalfEdge.cpp.i

Core/HalfEdge.s: Core/HalfEdge.cpp.s

.PHONY : Core/HalfEdge.s

# target to generate assembly for a file
Core/HalfEdge.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/HalfEdge.cpp.s
.PHONY : Core/HalfEdge.cpp.s

Core/OBJFileReader.o: Core/OBJFileReader.cpp.o

.PHONY : Core/OBJFileReader.o

# target to build an object file
Core/OBJFileReader.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/OBJFileReader.cpp.o
.PHONY : Core/OBJFileReader.cpp.o

Core/OBJFileReader.i: Core/OBJFileReader.cpp.i

.PHONY : Core/OBJFileReader.i

# target to preprocess a source file
Core/OBJFileReader.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/OBJFileReader.cpp.i
.PHONY : Core/OBJFileReader.cpp.i

Core/OBJFileReader.s: Core/OBJFileReader.cpp.s

.PHONY : Core/OBJFileReader.s

# target to generate assembly for a file
Core/OBJFileReader.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/OBJFileReader.cpp.s
.PHONY : Core/OBJFileReader.cpp.s

Core/Parser.o: Core/Parser.cpp.o

.PHONY : Core/Parser.o

# target to build an object file
Core/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Parser.cpp.o
.PHONY : Core/Parser.cpp.o

Core/Parser.i: Core/Parser.cpp.i

.PHONY : Core/Parser.i

# target to preprocess a source file
Core/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Parser.cpp.i
.PHONY : Core/Parser.cpp.i

Core/Parser.s: Core/Parser.cpp.s

.PHONY : Core/Parser.s

# target to generate assembly for a file
Core/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Parser.cpp.s
.PHONY : Core/Parser.cpp.s

Core/Point.o: Core/Point.cpp.o

.PHONY : Core/Point.o

# target to build an object file
Core/Point.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Point.cpp.o
.PHONY : Core/Point.cpp.o

Core/Point.i: Core/Point.cpp.i

.PHONY : Core/Point.i

# target to preprocess a source file
Core/Point.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Point.cpp.i
.PHONY : Core/Point.cpp.i

Core/Point.s: Core/Point.cpp.s

.PHONY : Core/Point.s

# target to generate assembly for a file
Core/Point.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Point.cpp.s
.PHONY : Core/Point.cpp.s

Core/Solid.o: Core/Solid.cpp.o

.PHONY : Core/Solid.o

# target to build an object file
Core/Solid.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Solid.cpp.o
.PHONY : Core/Solid.cpp.o

Core/Solid.i: Core/Solid.cpp.i

.PHONY : Core/Solid.i

# target to preprocess a source file
Core/Solid.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Solid.cpp.i
.PHONY : Core/Solid.cpp.i

Core/Solid.s: Core/Solid.cpp.s

.PHONY : Core/Solid.s

# target to generate assembly for a file
Core/Solid.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Solid.cpp.s
.PHONY : Core/Solid.cpp.s

Core/SolidDelegate.o: Core/SolidDelegate.cpp.o

.PHONY : Core/SolidDelegate.o

# target to build an object file
Core/SolidDelegate.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/SolidDelegate.cpp.o
.PHONY : Core/SolidDelegate.cpp.o

Core/SolidDelegate.i: Core/SolidDelegate.cpp.i

.PHONY : Core/SolidDelegate.i

# target to preprocess a source file
Core/SolidDelegate.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/SolidDelegate.cpp.i
.PHONY : Core/SolidDelegate.cpp.i

Core/SolidDelegate.s: Core/SolidDelegate.cpp.s

.PHONY : Core/SolidDelegate.s

# target to generate assembly for a file
Core/SolidDelegate.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/SolidDelegate.cpp.s
.PHONY : Core/SolidDelegate.cpp.s

Core/StringTokenizer.o: Core/StringTokenizer.cpp.o

.PHONY : Core/StringTokenizer.o

# target to build an object file
Core/StringTokenizer.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/StringTokenizer.cpp.o
.PHONY : Core/StringTokenizer.cpp.o

Core/StringTokenizer.i: Core/StringTokenizer.cpp.i

.PHONY : Core/StringTokenizer.i

# target to preprocess a source file
Core/StringTokenizer.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/StringTokenizer.cpp.i
.PHONY : Core/StringTokenizer.cpp.i

Core/StringTokenizer.s: Core/StringTokenizer.cpp.s

.PHONY : Core/StringTokenizer.s

# target to generate assembly for a file
Core/StringTokenizer.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/StringTokenizer.cpp.s
.PHONY : Core/StringTokenizer.cpp.s

Core/TopologyException.o: Core/TopologyException.cpp.o

.PHONY : Core/TopologyException.o

# target to build an object file
Core/TopologyException.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/TopologyException.cpp.o
.PHONY : Core/TopologyException.cpp.o

Core/TopologyException.i: Core/TopologyException.cpp.i

.PHONY : Core/TopologyException.i

# target to preprocess a source file
Core/TopologyException.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/TopologyException.cpp.i
.PHONY : Core/TopologyException.cpp.i

Core/TopologyException.s: Core/TopologyException.cpp.s

.PHONY : Core/TopologyException.s

# target to generate assembly for a file
Core/TopologyException.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/TopologyException.cpp.s
.PHONY : Core/TopologyException.cpp.s

Core/Trait.o: Core/Trait.cpp.o

.PHONY : Core/Trait.o

# target to build an object file
Core/Trait.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Trait.cpp.o
.PHONY : Core/Trait.cpp.o

Core/Trait.i: Core/Trait.cpp.i

.PHONY : Core/Trait.i

# target to preprocess a source file
Core/Trait.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Trait.cpp.i
.PHONY : Core/Trait.cpp.i

Core/Trait.s: Core/Trait.cpp.s

.PHONY : Core/Trait.s

# target to generate assembly for a file
Core/Trait.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Trait.cpp.s
.PHONY : Core/Trait.cpp.s

Core/Vertex.o: Core/Vertex.cpp.o

.PHONY : Core/Vertex.o

# target to build an object file
Core/Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Vertex.cpp.o
.PHONY : Core/Vertex.cpp.o

Core/Vertex.i: Core/Vertex.cpp.i

.PHONY : Core/Vertex.i

# target to preprocess a source file
Core/Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Vertex.cpp.i
.PHONY : Core/Vertex.cpp.i

Core/Vertex.s: Core/Vertex.cpp.s

.PHONY : Core/Vertex.s

# target to generate assembly for a file
Core/Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/halfedge.dir/build.make CMakeFiles/halfedge.dir/Core/Vertex.cpp.s
.PHONY : Core/Vertex.cpp.s

Subdivision/Subdivision.o: Subdivision/Subdivision.cpp.o

.PHONY : Subdivision/Subdivision.o

# target to build an object file
Subdivision/Subdivision.cpp.o:
	$(MAKE) -f CMakeFiles/cse570project2.dir/build.make CMakeFiles/cse570project2.dir/Subdivision/Subdivision.cpp.o
.PHONY : Subdivision/Subdivision.cpp.o

Subdivision/Subdivision.i: Subdivision/Subdivision.cpp.i

.PHONY : Subdivision/Subdivision.i

# target to preprocess a source file
Subdivision/Subdivision.cpp.i:
	$(MAKE) -f CMakeFiles/cse570project2.dir/build.make CMakeFiles/cse570project2.dir/Subdivision/Subdivision.cpp.i
.PHONY : Subdivision/Subdivision.cpp.i

Subdivision/Subdivision.s: Subdivision/Subdivision.cpp.s

.PHONY : Subdivision/Subdivision.s

# target to generate assembly for a file
Subdivision/Subdivision.cpp.s:
	$(MAKE) -f CMakeFiles/cse570project2.dir/build.make CMakeFiles/cse570project2.dir/Subdivision/Subdivision.cpp.s
.PHONY : Subdivision/Subdivision.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cse570project2"
	@echo "... halfedge"
	@echo "... Core/Edge.o"
	@echo "... Core/Edge.i"
	@echo "... Core/Edge.s"
	@echo "... Core/FException.o"
	@echo "... Core/FException.i"
	@echo "... Core/FException.s"
	@echo "... Core/Face.o"
	@echo "... Core/Face.i"
	@echo "... Core/Face.s"
	@echo "... Core/HalfEdge.o"
	@echo "... Core/HalfEdge.i"
	@echo "... Core/HalfEdge.s"
	@echo "... Core/OBJFileReader.o"
	@echo "... Core/OBJFileReader.i"
	@echo "... Core/OBJFileReader.s"
	@echo "... Core/Parser.o"
	@echo "... Core/Parser.i"
	@echo "... Core/Parser.s"
	@echo "... Core/Point.o"
	@echo "... Core/Point.i"
	@echo "... Core/Point.s"
	@echo "... Core/Solid.o"
	@echo "... Core/Solid.i"
	@echo "... Core/Solid.s"
	@echo "... Core/SolidDelegate.o"
	@echo "... Core/SolidDelegate.i"
	@echo "... Core/SolidDelegate.s"
	@echo "... Core/StringTokenizer.o"
	@echo "... Core/StringTokenizer.i"
	@echo "... Core/StringTokenizer.s"
	@echo "... Core/TopologyException.o"
	@echo "... Core/TopologyException.i"
	@echo "... Core/TopologyException.s"
	@echo "... Core/Trait.o"
	@echo "... Core/Trait.i"
	@echo "... Core/Trait.s"
	@echo "... Core/Vertex.o"
	@echo "... Core/Vertex.i"
	@echo "... Core/Vertex.s"
	@echo "... Subdivision/Subdivision.o"
	@echo "... Subdivision/Subdivision.i"
	@echo "... Subdivision/Subdivision.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

